### ISSUE TITLE
pdfium-cli info: performance question

### ISSUE THREAD

**Issue by msageryd** [klippa-app/pdfium-cli#14]
`pdfium-cli info` takes about 1.3-1.4 seconds to run on a 20 page pdf on my M2 Mac. This is when I call pdfium-cli from a spawned child-process in Node-js. If I run the command directly at the command line it takes about 0.9 sec.

The same document takes 0.3-0-4 seconds to parse with pdfjs. (https://github.com/mozilla/pdf.js) Pdfjs is Mozillas pure javascript library, it should probably be slower than pdfium-cli. Is this a WebAssembly thing, or could it be some problem with pdfium-cli? The pdfium-cli version I'm running is built from source (3ecdc9e) without any build flags.

Here is the pdfium-cli command (no timing difference between text and json):
`pdfium-cli info ./test.pdf --output-type json`

Here is roughly the code I'm running for pdfjs:
```
  const loadingTask = pdfjsLib.getDocument({
    data: fileBuffer.buffer,
  });

  const doc = await loadingTask.promise;
  const numPages = doc.numPages;

  for (let pageNum = 1; pageNum <= numPages; pageNum++) {
    const page = await doc.getPage(pageNum);
    const viewport = page.getViewport({ scale: 1.0 });

    const { width, height } = viewport;
    const pageData = { pageNum, width, height };

    console.log(pageData);
  }
```

**Comment by jerbob92** [comment]
Comparing the WebAssembly version to JS is not a fair comparison indeed because the WebAssembly runtime that we use also can't be compared to the WebAssembly runtime that you have in your browser. The runtime that we use (Wazero) is fairly new and the compiler is not optimized yet. They are working hard on a new compiler backend: https://github.com/tetratelabs/wazero/issues/1496

This should bring speed improvements when released.

The pdfium-cli was mainly built for ourself to do quick PDF operations locally, not really for direct integration in applications (we use go-pdfium for that directly), that's why speed was never an issue for us, using WebAssembly mainly meant very easy distribution which was more important for us.

If you want better speeds now, you should use the CGO build.

**Comment by msageryd** [comment]
Update.
It was a WebAssembly issue, indeed.

I built pdfium-cli with `-tags pdfium_cli_use_cgo` to get rid of webAssembly.
The time for command line execution is now down to 0.2 sec
The time for a Node child process is now down 50% to 0.6-0.7 sec.

Closing this.
